### ISSUE TITLE
selfhosted: this.member_name not supported

### ISSUE THREAD

**Issue by mnlrsn** [SerenityOS/jakt#638]
Compilation error with this snippet:
```
class C {
    a: u8

    function f(this) {
        let b: u8 = this.a
    }
}
```
Error:
```
 4 |     function f(this) {
 5 |         let b: u8 = this.a
                         ^- Unsupported expression
 6 |     }
```

**Comment by mnlrsn** [comment]
The use case for this notation is maybe clearer in a for loop:
```
for i in 0..this.a {
}
```
If the dot notation is used (`.a`) then the result is three dots in a row, which can be seen less clear on a quick reading.

**Comment by cybergsus** [comment]
Fixed by 7fc6c8e.

**Comment by mnlrsn** [comment]
I still see the issue. The error message has changed, though:
```
 4 |     function f(this) {
 5 |         let b: u8 = this.a
                         ^- Type mismatch: expected ‘u8’, but got ‘C’
 6 |     }
```

**Comment by mnlrsn** [comment]
Fixed.
